language: node_js

node_js:
- node

script:
- yarn build
- yarn test

deploy:
  provider: npm
  skip_cleanup: true
  email:
    secure: owDNheKpx4pt9PiAkYS79x0yYzmI6/PYdiQR+kH/nHIo+LedvINiyMX3lHc062KEQ4cRIMHfNA/64vCDZoRJrC6FkIasXKdeOOvpGLMhWPmkbbMkB0ITZ8yBlw2h/h+N7w0EoCF4U0oWwNzjg2LfyfZdK//rSe1kKZ4FUU6kTNAGBgC/4I8kPdT6YWat6O8hd35xHXhDh7t+KX54OwRvq5Cnl/uos0djUK/R5rIdrRbUu1AaH0UHuPYfV8NdO62RAJ0c4Qoajs0JJR6OHLNzQzFeGqCfUq/IBQgP1M8Mo/+E5od4FI9idL9mlI5j4pX80FT3UsK14OVzsEHz4JrvNEhWVwFVeWeW9C5laBWtZrF4do+fKSL13sq51gm2V4meQlaT2FG9lOmTWKUNAoGL1qQbZWXRzusl76w+jnyv91r8MKNmed6AGUQpAM6g3H1ypAt5pr9aflhpW+cegFPZDuGQjDmJIg0QsD4sXcPw6zJao17QybLbebd4m2Z2RBaSekuHV6vVnShfuce2BVbh4PEvh8vXdLwa5Vz7KNR+HM7Th2RZcKGCjj/nZf8O/ZDQgu9aI93pWuNwVJls7BdhxclRz0SzJwzq25HO3+9klASrpLAAhR1hoDKt2HItzMBP0fwSraj6ekLaIHYVgRQ/JansxyX6zQWbApACgRbaL5c=
  api_key:
    secure: N9qRU4TLTntxJ/0tbff7Ts6ADTR1vp81D5kqiOIKdghujX4bv3Pq4efR5sCy+jsp/pBEX3LQb0kD5LLlCsj0GPZoE2HWsr++2RtWYDJR3RrAPS42L5a0a0vm9CMAyhaLc1zWr8siAbPfBKZSAn/u1ppHx/9R7r0U6+8Dlfey0rEpgqwhPPJuTAaFcqVP6PAO96YXzsMgk2krtyoIw29UQhQOoH8XP+tPlzrRNLPAmtQ3HNwwVhZdS/P8Quzpxad+q268SNMgqCVNmm5AoGDVUYaPi3OLk75wuE6LXF0p1t+1Yf+FY9ZTaabIlGfr6Qkk79BzyjUtfXbneUvpzs59dtD2coXZ1QjiTfji2NctnJzICOPJMyyV694iLd3y+xaA+EcYpuT2cD27OIs/BdSQ9xacR3K8i+gJmoP2Mpnv/j8+1sNzPn/V4UEm7I34O2wudLxZ+WHCA13+nGoshe0QwAlfZ1+IGbMk3pgkVMSk2rM+5LrIf6b2XgRm1LOuxEFt3BCdenQfiyvg80rlp2amiytdyPkdnqDbe9UZoCJSuASdGZn+RJwPlzR27Gm3AU8MB+gxMP0NGRU7sBV5UsL5ghlPTH1eUoquXGDgfv1uvt7WGRXgbwWDyEaeHVB3TWqJ79jZrKy+5lGn/sE7RYgH0Sa4ve81Ji83LfHm6OcgkG8=
  on:
    tags: true
